### ISSUE TITLE
Mermaid example breaks in chrome.

### ISSUE THREAD

**Issue by hartzell** [bwmarrin/MkDocsPlus#3]
Thanks for the great resource.

The mermaid example fails on Chrome for reasons described in [this mermaid issue](https://github.com/knsv/mermaid/issues/281).

They've made a [new release](https://github.com/knsv/mermaid/releases/tag/0.5.7)  to deal with it, the example works again (on my Yosemite mac w/ a current Chrome) after I update the mermaid files.

**Comment by bwmarrin** [comment]
Awesome! I'll update it when I can.

**Comment by bwmarrin** [comment]
Well, I finally found some time :) I've ugprade mkdocs and also mermaid but now I can't seem to get it to work properly at all :(  I'll keep working on trying to get it going again.

Do you have it working using the latest versions?

**Comment by bwmarrin** [comment]
Nevermind that, I've got all working now :)
