### ISSUE TITLE
Q: Is it possible to fetch real data (e.g. from Jenkins server) for charts examples?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [bwmarrin/MkDocsPlus#4]
Is it possible to feed `data.js` in chartjs/chartisjs examples with real data from a Jenkins server?

Jenkins server provides several APIs json, xml, python.

Here is an [stackoverflow example](http://stackoverflow.com/questions/12944403/how-to-get-progress-bar-data-for-a-running-jenkins-job-through-the-api).

I would like to integrate a chart of executed test (passed/failed) from Jenkins builds, e.g. like this:

![image](https://cloud.githubusercontent.com/assets/5635462/23025474/6b821346-f45e-11e6-8214-25f05ff5da13.png)

Actually the idea behind my question is to integrate a [Jenkins job dashboard](https://github.com/kj187/dashing-jenkins_job) into MkDocs which I am recently abusing as a light test management solution for my Robot Framework tests cases.

**Comment by bwmarrin** [comment]
Hey, good question :) I'm curious too, now.  Though this is probably beyond the scope of this little example project here.  

I'm far from a Javascript expert (or even a novice, honestly) but I think maybe something along these lines?


Inside data.js you would need to make an ajax call to the Jenkin's JSON API to pull the data you want, then you process that data to format it like the existing data array and then hand it over to the Chartist Chart() function.

**Comment by Tset-Noitamotua** [comment]
Many thanks for your reply. I will report back here if I get something working.
