### ISSUE TITLE
Client-Site Templating via Mustache

### ISSUE THREAD

**Issue by oxr463** [bwmarrin/MkDocsPlus#6]
See: https://github.com/janl/mustache.js

**Comment by bwmarrin** [comment]
I'm not exactly sure what you're asking or saying here.  Could you elaborate with some added context?

**Comment by oxr463** [comment]
> 
> 
> I'm not exactly sure what you're asking or saying here. Could you elaborate with some added context?

An example of using mustache.js with Mkdocs, but in the browser, e.g., AJAX call to populate a table.

**Comment by bwmarrin** [comment]
Oh, I do not have an example and I hate to say it but I don't really have the free time currently to create one.  If you wanted to create an example and PR it into the repo I'd be happy to add one it.

But in general, mkdocs just creates a static html/css/js site.  So you can add any js library into the mix and have it work.  You can look at some of the other examples for a rough outline of what's needed but it's fairly straight forward in that you just include the js library, then add whatever js code into the mkdocs files that are needed for that library.  Just like for any other basic html/css/js website would need.
